# Config do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ricebowl
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Config do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log de inicialização
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Config JWT
api.security.token.secret=${JWT_SECRET:ricebowl-dev-secret-key}