# Config do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ricebowl
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Config do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Log de inicialização
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Config JWT
api.security.token.secret=${JWT_SECRET:ricebowl-dev-secret-key}

logging.level.org.springframework.security=DEBUG

# Para garantir que o flyway rode antes de tudo e para evitar conflitos 
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Configurações do MinIO / S3
minio.endpoint=http://localhost:9000
minio.access-key=ricebowl
minio.secret-key=ricebowl_secret
minio.bucket-name=ricebowl-bucket

# Limites de upload de arquivos (Tamanho máximo)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB